version: '3'
services:
  electrumweb:
    build:
      context: .
      dockerfile: ./electrum.Dockerfile
    working_dir: /var/www/html
    volumes:
      - /c/work_ids/zeIDS/ElectrumWEB/webcodes:/var/www/html
      - /c/work_ids/zeIDS:/ourdata
    command: python3 main.py --address='0.0.0.0'
    ports: 
    # - 8888:80
      - "8888:8888"
    #src_host_port/dest_container_port
#     networks:
#       - monreseau

# networks: 
#   monreseau: